import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./Providers/ThemeProvider";
import NavbarWrapper from "@/components/NavbarWrapper";
import { cookies } from "next/headers";
import AuthProvider from "./Providers/AuthProvider";
import UsernameProvider from "./Providers/UsernameProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const getTheme = async () => {
        const CookieStore = await cookies()
        const themeCookie = CookieStore.get('theme')?.value
        return themeCookie ? themeCookie : 'light';
    };

    const theme = await getTheme();
    
    return (
        <html lang="en" className={theme === 'dark' ? 'dark' : ''}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased font-lato`}
            >
                <ThemeProvider initialTheme={theme}>
                    <AuthProvider>
                        <UsernameProvider>
                            <NavbarWrapper />
                            {children}
                        </UsernameProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
